# This is a basic workflow to help you get started with Actions

name: Build Windows

defaults:
  run:
    shell: msys2 {0}
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
            repository: cloudreve/Cloudreve
            submodules: recursive
            ref: 3.6.2
      
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          install: mingw-w64-clang-x86_64-toolchain git zip mingw-w64-clang-x86_64-go  mingw-w64-clang-x86_64-nodejs mingw-w64-clang-x86_64-yarn
      # Runs a set of commands using the runners shell
      - name: Build Frontend
        working-directory: assets
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          CI: false
        run: |
          yarn
          yarn run build
          cd build
          find . -name "*.map" -type f -delete
          cd ../..
          zip -r - assets/build >assets.zip
        
      - name: Build Backend
        env:
          CC: clang
          CXX: clang++
          AR: llvm-ar
        run: |
          export COMMIT_SHA=$(git rev-parse --short HEAD)
          export VERSION=$(git describe --tags)
          go build -a -o cloudreve -ldflags "-s -w -X 'github.com/cloudreve/Cloudreve/v3/pkg/conf.BackendVersion=$VERSION' -X 'github.com/cloudreve/Cloudreve/v3/pkg/conf.LastCommit=$COMMIT_SHA'"
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
         name: cloudreve
         path: cloudreve.exe
